---@type table
local M = {}

---@param color string #Color descriptor
---@param mode? "dark"|"light"|"shared" #Color mode ("dark" | "light" | "shared")
local gcol = function(color, mode)
  local pallete = M.colors(mode and mode or "dark")
  if pallete[color] then
    return pallete[color]
  else
    return nil
  end
end
M.gcol = gcol

local COLORS = {
      ["dark"] = {
    -- bg = '#001b24',
    -- bg = '#00253d',
    -- bg = '#09151b',
    bg = "#181818",
    bg1 = "#181818",
    fg = "#DBDBDB",
    fg1 = "#DBDBDB",
    linefg = "#DBDBDB",
    linebg = "#292929",
    red = "#ff5c57",
    yellow = "#DCCC9F",
    green = "#90CEBB",
    blue = "#92BAEA",
    blue2 = "#004e75",
    cyan = "#9aedfe",
    purple = "#A398DE",
    orange = "#ff9f43",
    brown = "#b2643c",
    pink = "#CCA0CE",
    invisibles = "#65737E",
    caret = "#54555e",
    guides = "#424242",
    lsp_background = "#54555e",
    line_highlight = "#171717",
    normal = "#57c7ff",
    visual = "#68A247",
    insert = "#ff5c57",
    command = "#f5e000",
  },
      ["light"] = {
    bg = "#eff0eb",
    bg1 = "#cdd0c9",
    fg = "#282a36",
    fg1 = "#000000",
    linefg = "#585853",
    linebg = "#cacbc8",
    red = "#ff5c57",
    yellow = "#CF9C00",
    green = "#2DAE58",
    blue = "#09A1ED",
    blue2 = "#004e75",
    cyan = "#13BBB7",
    purple = "#F767BB",
    orange = "#F76D47",
    brown = "#C17E70",
    pink = "#FF5370",
    invisibles = "#E7EAEC",
    caret = "#272727",
    selection = "#c4d8e2",
    guides = "#B0BEC5",
    lsp_background = "#e2e3e9",
    line_highlight = "#ECF0F1",
    codeDelimiter = "#78787e",
    normal = "#09A1ED",
    visual = "#2DAE58",
    insert = "#F76D47",
    command = "#CF9C00",
  },
      ["shared"] = {
    gray = "#535353",
    gray1 = "#979791",
    fg3 = "#e2e4e5",
    disabled = "#464B5D",
    line_numbers = "#6D6D6D",
    selection = "#464B5D",
    white = "#eff0eb",
    black = "#101010",
    yellowfaded = "#ebcb8b",
    comments = "#6D6D6D",
    cursorline = "#292929",
    dark_gray = "#171717",
  },
}

---@param m "dark"|"light"|"shared" #Color mode ("dark" | "light" | "shared")
---@return table
M.colors = function(m)
  ---@type {[string]: string}
  local c = {
        ["none"] = "",
        ["fg1"] = COLORS[m]["fg1"],
        ["fg2"] = COLORS[m]["fg"],
        ["fg3"] = COLORS["shared"]["fg3"],
        ["disabled"] = COLORS["shared"]["disabled"],
        ["line_numbers"] = COLORS["shared"]["line_numbers"],
        ["selection"] = COLORS["shared"]["selection"],
        ["white"] = COLORS["shared"]["white"],
        ["gray"] = COLORS["shared"]["gray"],
        ["gray1"] = COLORS["shared"]["gray1"],
        ["black"] = COLORS["shared"]["black"],
        ["red"] = COLORS[m]["red"],
        ["green"] = COLORS[m]["green"],
        ["yellow"] = COLORS[m]["yellow"],
        ["yellowfaded"] = COLORS[m]["yellowfaded"],
        ["blue"] = COLORS[m]["blue"],
        ["cyan"] = COLORS[m]["cyan"],
        ["purple"] = COLORS[m]["purple"],
        ["orange"] = COLORS[m]["orange"],
        ["brown"] = COLORS[m]["brown"],
        ["comments"] = COLORS["shared"]["comments"],
        ["error"] = COLORS[m]["red"],
        ["pink"] = COLORS[m]["pink"],
        ["incsearch"] = COLORS[m]["yellow"],
        ["search"] = COLORS[m]["yellow"],
        ["linebg"] = COLORS[m]["linebg"],
        ["linefg"] = COLORS[m]["linefg"],
        ["Constant"] = COLORS[m]["fg"],
        ["String"] = COLORS[m]["pink"],
        ["Character"] = COLORS[m]["yellow"],
        ["Boolean"] = COLORS[m]["fg"],
        ["Float"] = COLORS[m]["fg"],
        ["Identifier"] = COLORS[m]["fg"],
        ["Function"] = COLORS[m]["yellow"],
        ["Statement"] = COLORS[m]["green"],
        ["Conditional"] = COLORS[m]["red"],
        ["Repeat"] = COLORS[m]["yellow"],
        ["Label"] = COLORS[m]["yellow"],
        ["Operator"] = COLORS[m]["fg"],
        ["Number"] = COLORS[m]["green"],
        ["Keyword"] = COLORS[m]["green"],
        ["Exception"] = COLORS[m]["red"],
        ["PreProc"] = COLORS[m]["white"],
        ["cursorline"] = COLORS[m]["cursorline"],
        ["Include"] = COLORS[m]["blue"],
        ["Define"] = COLORS[m]["purple"],
        ["Macro"] = COLORS[m]["red"],
        ["PreCondit"] = COLORS[m]["purple"],
        ["Type"] = COLORS[m]["blue"],
        ["StorageClass"] = COLORS[m]["yellow"],
        ["Structure"] = COLORS[m]["purple"],
        ["Typedef"] = COLORS[m]["yellow"],
        ["Special"] = COLORS[m]["blue"],
        ["SpecialChar"] = COLORS[m]["yellow"],
        ["Tag"] = COLORS[m]["orange"],
        ["Delimiter"] = COLORS[m]["fg"],
        ["SpecialComment"] = COLORS[m]["yellow"],
        ["Debug"] = COLORS[m]["red"],
        ["Todo"] = COLORS[m]["orange"],
        ["Underlined"] = COLORS[m]["blue"],
        ["bg"] = COLORS[m]["bg"],
        ["bg1"] = COLORS[m]["bg1"],
        ["fg"] = COLORS[m]["fg"],
        ["invisibles"] = COLORS[m]["invisibles"],
        ["caret"] = COLORS[m]["caret"],
        ["guides"] = COLORS[m]["guides"],
        ["lsp_background"] = COLORS[m]["lsp_background"],
        ["line_highlight"] = COLORS[m]["line_highlight"],
        ["accent"] = COLORS[m]["blue"],
        ["htmlBold"] = COLORS[m]["yellow"],
        ["url"] = COLORS[m]["red"],
        ["link"] = COLORS[m]["green"],
        ["heading"] = COLORS[m]["blue"],
        ["codeDelimiter"] = COLORS[m]["purple"],
        ["TSVariable"] = COLORS[m]["fg"],
        ["TSField"] = COLORS[m]["blue"],
        ["TSProperty"] = COLORS[m]["purple"],
        ["TSParameter"] = COLORS[m]["fg"],
        ["TSKeywordOperator"] = COLORS[m]["yellow"],
        ["blue2"] = COLORS[m]["blue2"],
  }
  return c
end

return M
